import type { PagesMiddlewareContext } from "./context.js";

/**
 * Headers for the responses the Functions layer itself produces.
 *
 * ## Why this is a module and not a root middleware
 *
 * It began as `functions/_middleware.ts`, which Cloudflare runs "in front of
 * static files" as well as Functions. That is a wider scope than the file
 * wanted: it exists because a JSON body and a generated avatar do not get the
 * headers `public/_headers` gives documents, and it stamped
 * `default-src 'none'` on any response that arrived without a policy. Whether
 * that could ever hit a *document* depended on an ordering the platform
 * documents in two places and guarantees in neither: `_headers` is not applied
 * to responses generated by Functions, root middleware does run in front of
 * static assets, and which of those two facts wins for a static asset that a
 * middleware wrapped is not stated anywhere.
 *
 * If the bad ordering were the real one, every HTML page would have shipped with
 * `default-src 'none'`: no stylesheet, no script, and the cache rules for
 * `/assets/*` gone with them. Nothing in the repository could have caught it,
 * because no local server applies `_headers` at all.
 *
 * The fix is to stop depending on the answer. Middleware in `functions/api/`
 * and `functions/avatar/` matches only those two subtrees, so a document never
 * passes through this code and the question cannot arise. The policy is
 * unchanged; only the set of responses it can reach is smaller, and that set is
 * now exactly the one the file was written for.
 */

/** Applies to every response this layer produces. */
const COMMON: Readonly<Record<string, string>> = {
  "x-content-type-options": "nosniff",
  "x-frame-options": "DENY",
  "referrer-policy": "strict-origin-when-cross-origin",
  "cross-origin-opener-policy": "same-origin",
  "permissions-policy":
    "accelerometer=(), autoplay=(), browsing-topics=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()",
};

/**
 * The policy for a response the Functions layer generated.
 *
 * `default-src 'none'` because nothing here is a document that loads anything:
 * a JSON body has no subresources, and the confirmation page is deliberately
 * self-contained with no stylesheet and no script. The generated avatar is an
 * SVG with no external reference. A policy this tight is only possible because
 * the layer's own outputs are this plain, and it means a mistake in one of them
 * cannot turn into a loaded resource.
 */
export const FUNCTION_CSP =
  "default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'";

/** Run a route and add the headers above to whatever it answered. */
export async function withFunctionHeaders(
  context: PagesMiddlewareContext,
): Promise<Response> {
  const response = await context.next();

  // A new Headers object: the response from `next()` may be immutable.
  const headers = new Headers(response.headers);
  for (const [name, value] of Object.entries(COMMON)) {
    headers.set(name, value);
  }
  if (!headers.has("content-security-policy")) {
    headers.set("content-security-policy", FUNCTION_CSP);
  }

  /*
   * A submission is a POST and its answer reflects what the caller sent, so it
   * must not be stored by any cache in the path. GET responses carry their own
   * cache policy and are left alone.
   */
  if (context.request.method !== "GET" && !headers.has("cache-control")) {
    headers.set("cache-control", "no-store");
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
